### PR TITLE
Keeping sent a package during the stream for firewall hole punching

### PR DESCRIPTION
**Pull request by CosbyBs86**
I added the keep alive hole punching (default 30 seconds). It is not possible to create a dedicated thread for this operation because the socket is bound in Receiver() method and it might collide with the blocking Receive operation. I added a check in the receiver loop. If the time between the last keep alive and the current time is >= with the defined timeout (30 seconds as default) a package is sent.

### CODE REVIEW

**Comment by CosbyBs86** [comment]
@Touseefelahi here we go for the keep alive firewall hole punching.

**Comment by CosbyBs86** [comment]
Thank you @Touseefelahi 
Do you have any chance to make a release with all those changes and publish it as new nuget package?

**Comment by Touseefelahi** [comment]
You're welcome @CosbyBs86 
If you are done with your changes then I'll do it by the end of this week

**Comment by CosbyBs86** [comment]
Yes @Touseefelahi I finished all the changes. For me you can go with the new release.

**Comment by CosbyBs86** [comment]
@Touseefelahi  if you share your email I'll send my contacts. I don't want to publish them here ;)

**Comment by Touseefelahi** [comment]
sure, contact me at touseefelahi@ymail.com

**Pull request merged**
